name: q_jobs
description: "Find the perfect job"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  flutter_native_splash: ^2.4.4
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"  # Ensures Android icons are generated
  ios: true  # Ensures iOS icons are generated
  image_path: "assets/icon/app_icon.png"  # Primary image for both platforms
  adaptive_icon_foreground: "assets/icon/app_icon.png"  # Foreground for Android adaptive icons
  adaptive_icon_background: "#FFFFFF"  # Background color for Android adaptive icons
  min_sdk_android: 21  # Minimum SDK version for Android


flutter_native_splash:
  color: "#ffffff"  # Background color
  image: assets/icon/splash_image.png  # Path to your splash image
  android: true  # Enable for Android
  ios: true  # Enable for iOS
  android_gravity: center  # Center the image on Android
  ios_content_mode: center  # Center the image on iOS
  fullscreen: true  # Enable fullscreen splash screen




flutter:
  uses-material-design: true
